// Styled MUI building blocks exposed to generated components
export const STYLED_COMPONENTS_SNIPPET = String.raw`
const StyledComponents = {
  BeautifulCard: (props) => React.createElement(MuiMaterial.Card, {
    ...props,
    sx: {
      borderRadius: designTokens.borderRadius.lg,
      boxShadow: 'none',
      border: '1px solid',
      borderColor: 'divider',
      overflow: 'hidden',
      transition: 'border-color 120ms ease',
      '&:hover': { borderColor: 'divider' },
      ...props.sx,
    },
  }),
  FormContainer: (props) => React.createElement(MuiMaterial.Box, {
    ...props,
    sx: {
      padding: designTokens.spacing.md,
      backgroundColor: 'transparent',
      borderRadius: designTokens.borderRadius.lg,
      boxShadow: 'none',
      border: 'none',
      '& .MuiTextField-root': {
        marginBottom: designTokens.spacing.sm,
      },
      ...props.sx,
    },
  }),
  PrimaryButton: (props) => React.createElement(MuiMaterial.Button, {
    variant: 'contained',
    size: 'small',
    disableElevation: true,
    ...props,
    sx: {
      borderRadius: designTokens.borderRadius.md,
      textTransform: 'none',
      fontWeight: 600,
      fontSize: '0.85rem',
      padding: '3px 8px',
      minHeight: '22px',
      minWidth: '40px',
      lineHeight: 1.2,
      whiteSpace: 'nowrap',
      '& .MuiButton-startIcon': { marginRight: 6 },
      boxShadow: 'none',
      ...props.sx,
    },
  }),
  SuccessButton: (props) => React.createElement(MuiMaterial.Button, {
    variant: 'contained',
    color: 'success',
    size: 'small',
    disableElevation: true,
    ...props,
    sx: {
      borderRadius: designTokens.borderRadius.md,
      textTransform: 'none',
      fontWeight: 600,
      fontSize: '0.85rem',
      padding: '3px 8px',
      minHeight: '22px',
      minWidth: '40px',
      lineHeight: 1.2,
      whiteSpace: 'nowrap',
      '& .MuiButton-startIcon': { marginRight: 6 },
      boxShadow: 'none',
      ...props.sx,
    },
  }),
  DangerButton: (props) => React.createElement(MuiMaterial.Button, {
    variant: 'contained',
    color: 'error',
    size: 'small',
    disableElevation: true,
    ...props,
    sx: {
      borderRadius: designTokens.borderRadius.md,
      textTransform: 'none',
      fontWeight: 600,
      fontSize: '0.85rem',
      padding: '3px 8px',
      minHeight: '22px',
      minWidth: '40px',
      lineHeight: 1.2,
      whiteSpace: 'nowrap',
      '& .MuiButton-startIcon': { marginRight: 6 },
      boxShadow: 'none',
      ...props.sx,
    },
  }),
  FloatingAction: (props) => React.createElement(MuiMaterial.Fab, {
    color: 'primary',
    size: 'small',
    ...props,
    sx: {
      position: 'fixed',
      right: 16,
      bottom: 16,
      boxShadow: 'none',
      ...props.sx,
    },
  }),
  ContentContainer: (props) => React.createElement(MuiMaterial.Box, {
    ...props,
    sx: {
      padding: designTokens.spacing.md,
      backgroundColor: 'transparent',
      minHeight: 'auto',
      '& > *:not(:last-child)': {
        marginBottom: designTokens.spacing.md,
      },
      ...props.sx,
    },
  }),
  SectionHeader: (props) => React.createElement(MuiMaterial.Typography, {
    variant: 'subtitle2',
    ...props,
    sx: {
      fontWeight: 500,
      fontSize: '0.89rem',
      letterSpacing: '0.04em',
      textTransform: 'uppercase',
      color: 'text.secondary',
      marginBottom: designTokens.spacing.xs,
      paddingBottom: '4px',
      position: 'relative',
      borderBottom: '1px solid',
      borderBottomColor: 'divider',
      display: 'inline-block',
      '&::after': {
        content: '""',
        position: 'absolute',
        left: 0,
        bottom: -1,
        width: '40px',
        height: '2px',
        background: 'linear-gradient(90deg, ' + designTokens.colors.primary[400] + ', rgba(14,165,233,0))',
        borderRadius: '1px',
      },
      ...props.sx,
    },
  }),
};
`;

